### PR TITLE
Include client script in installation, and README updates

### PR DESCRIPTION
**Pull request by Lizards**
Hi, thank you for this utility!  I've found it very useful.

I made a couple edits for your consideration:
- Include the `xdg-open.sh` client script in the installation
- In `xdg-open.sh`, derive user ID from `id --user` rather than `$UID` shell variable (also linted the script using `shellcheck`)
- Added `socat` as an optional dependency in the `PKGBUILD`
- Expanded the Docker example in the README, and a note for i3wm users on auto-starting the application
- Updated so `xdg-open-server.desktop` will be included by `make dist`

Would you consider putting this on the AUR?

### CODE REVIEW

**Comment by kitsunyan** [comment]
Oh, that's funny that someone found this tool useful! Actually, it's not perfect and I'm going to improve it a bit.

I think `/usr/lib/xdg-open-server` is more suitable location for `xdg-open.sh` than `/usr/share/xdg-open-server`. Don't you mind if I change it?

**Comment by Lizards** [comment]
No problem, I debated between `/usr/share` and `/usr/lib`.

Primarily I am using it to open links on my host machine from the Slack desktop app running in a Docker container.  Thanks!

**Comment by kitsunyan** [comment]
Ok. Moved to `/usr/lib/xdg-open-server/xdg-open` (`.sh` extension was dropped too).

I think I'll drop autotools, I just wanted to learn it, but now I think it's overkill for this project. Then I'll put it to AUR.

**Comment by kitsunyan** [comment]
https://aur.archlinux.org/packages/xdg-open-server/

**Pull request merged**
